# IMPORTANTE: No modificar ni borrar ni renombrar este archivo

all: a.out
	./a.out
	
a.out:
	gcc test_hw1.c -o a.out

apariciones: a.out
	./a.out a

mayor: a.out
	./a.out m

reverso: a.out
	./a.out r

ordenado: a.out
	./a.out o

clean:
	rm a.out