# IMPORTANTE: No modificar ni borrar ni renombrar este archivo

all: a.out
	./a.out
	
a.out:
	gcc test_hw0.c -o a.out

sumarDosNumeros: a.out
	./a.out s

positividad: a.out
	./a.out p

intervalo: a.out
	./a.out t

clean:
	rm a.out